var users = {
login: "jlock64",
id: 16665681,
avatar_url: "https://avatars.githubusercontent.com/u/16665681?v=3",
gravatar_id: "",
url: "https://api.github.com/users/jlock64",
html_url: "https://github.com/jlock64",
followers_url: "https://api.github.com/users/jlock64/followers",
following_url: "https://api.github.com/users/jlock64/following{/other_user}",
gists_url: "https://api.github.com/users/jlock64/gists{/gist_id}",
starred_url: "https://api.github.com/users/jlock64/starred{/owner}{/repo}",
subscriptions_url: "https://api.github.com/users/jlock64/subscriptions",
organizations_url: "https://api.github.com/users/jlock64/orgs",
repos_url: "https://api.github.com/users/jlock64/repos",
events_url: "https://api.github.com/users/jlock64/events{/privacy}",
received_events_url: "https://api.github.com/users/jlock64/received_events",
type: "User",
site_admin: false,
name: "Justin Lock",
company: null,
blog: null,
location: null,
email: null,
hireable: null,
bio: null,
public_repos: 14,
public_gists: 0,
followers: 0,
following: 0,
created_at: "2016-01-12T11:36:28Z",
updated_at: "2016-02-17T13:03:37Z"
}
